name: festhest
version: "0.0.0.1"
default-extensions:
  - BlockArguments
  - GADTs
  - LambdaCase
  - OverloadedStrings
  - QuasiQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
executables:
  festhest:
    main: Main.hs
    source-dirs: src-exe
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - bytestring
      - http-types
      - wai-extra
      - wai
      - yesod

    extra-libraries:
      - z
