name: festhest
version: "0.0.0.1"
default-extensions:
  - BlockArguments
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
executables:
  festhest:
    main: Main.hs
    source-dirs: src-exe
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - async
      - base
      - blaze-builder
      - blaze-html
      - bytestring
      - http-types
      - text
      - time
      - wai-extra
      - wai
      - yesod
      - yesod-form
      - yesod-auth
    extra-libraries:
      - z
