name: festhest
version: "0.0.0.1"
default-extensions:
  - OverloadedStrings
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
executables:
  festhest:
    main: Main.hs
    source-dirs: src-exe
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - yesod

    extra-libraries:
      - z
